name = "danielwaitwebsite"
account_id      = "9b31e0273bd94a2026dadba26d328a2b"
compatibility_date = "2025-04-24"
workers_dev     = true

# Main Worker script
main = "index.js"

# Static assets
assets = { directory = "./public" }

# KV Namespace for wait list data
kv_namespaces = [
  { binding = "WAIT_LIST_KV", id = "54bfa89034d949529cf36861e0746d5f" }
]